export const REQUEST_TODO_PENDING = "REQUEST_TODO_PENDING"
export const REQUEST_TODO_SUCCESS = "REQUEST_TODO_SUCCESS"
export const REQUEST_TODO_FAILED = "REQUEST_TODO_FAILED"
export const DELETE_SINGLE_TODO = "DELETE_SINGLE_TODO"