export const REQUEST_TODO_PENDING = "REQUEST_TODO_PENDING"
export const REQUEST_TODO_SUCCESS = "REQUEST_TODO_SUCCESS"
export const REQUEST_TODO_FAILED = "REQUEST_TODO_FAILED"

export const POST_CREATE_TODO_PENDING = "POST_CREATE_TODO_PENDING"
export const POST_CREATE_TODO_SUCCESS = "POST_CREATE_TODO_SUCCESS"
export const POST_CREATE_TODO_FAILED = "POST_CREATE_TODO_FAILED"

export const DELETE_TODO_PENDING = "DELETE_TODO_PENDING"
export const DELETE_TODO_SUCCESS = "DELETE_TODO_SUCCESS"
export const DELETE_TODO_FAILED = "DELETE_TODO_FAILED"